#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
FONT="Hack Nerd Font"                         # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3                                    # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar height=60 \
  color=$BAR_COLOR \
  shadow=$SHADOW \
  position=right \
  sticky=on \
  padding_right=18 \
  padding_left=18 \
  corner_radius=9 \
  y_offset=10 \
  margin=10 \
  blur_radius=20 \
  \
  --default updates=when_shown \
  icon.font="$FONT:Bold:14.0" \
  icon.color=$ICON_COLOR \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.font="$FONT:Semibold:13.0" \
  label.color=$LABEL_COLOR \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  popup.background.border_width=2 \
  popup.background.corner_radius=11 \
  popup.background.border_color=$POPUP_BORDER_COLOR \
  popup.background.color=$POPUP_BACKGROUND_COLOR \
  popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

sketchybar --add item separator right \
  --set separator icon= \
  icon.font="Hack Nerd Font:Regular:16.0" \
  background.padding_left=15 \
  background.padding_right=15 \
  label.drawing=off \
  icon.color=$GREEN

sketchybar --add item volume right \
  --set volume script="$ITEM_DIR/volume.sh" \
  --subscribe volume volume_change

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
